version: "3.8"

services:
  mysql:
    image: mysql:5.7
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_general_ci,
        --init-connect='SET NAMES UTF8;',
        --innodb-flush-log-at-trx-commit=0,
      ]
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=12345678
      - LANG=C.UTF-8
    ports:
      - "3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
